export const ACTION_TYPES = {
  SIGN_IN: "SIGN_IN",
  START_LOADING: "START_LOADING",
  STOP_LOADING: "STOP_LOADING",
  UPDATE_AUTH_TOKEN: "UPDATE_AUTH_TOKEN",
  UPDATE_USER_DETAILS : "UPDATE_USER_DETAILS",
  SIGN_OUT: "SIGN_OUT",
  SIGNIN_FAILED: "SIGNIN_FAILED",
  CLEAR_ERROR: "CLEAR_ERROR"
};
